ENV["EMAIL_USER_NAME"] = "answerawesome"
ENV["EMAIL_PASSWORD"] = "Sup3r$ecret$$"
ENV['TWITTER_CONSUMER_KEY'] = "mvLhEhyNTJNTDMZXPEMl29Lcc"
ENV['TWITTER_CONSUMER_SECRET'] = "S6hUog52BVAGz6CTi2KBHlgb0exicYnipNOGUIAgUF8YienBz0"
